config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'festivals#home'
  get 'users/:id' => 'festivals#profile', as: 'profile'
  resources :festivals
  post 'festivals/:id' => 'festivals#favorite', as: 'favorite'
  get 'users/:id/fav' => 'festivals#saved', as: 'saved'
  delete 'users/:id/fav' => 'festivals#deleted', as: 'deleted'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
end

app/models/festival.rb
class Festival < ApplicationRecord
    has_many :users, :through => :favorites
    has_many :favorites
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :favorites
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    if user_signed_in?
      user = current_user.id
      festivals_path
    else
      new_user_session_path
  end
end
end

app/controllers/festivals_controller.rb
class FestivalsController <ApplicationController
    include HTTParty
    include Wikipedia
        

    def home

    end

    def index
        @seatgeek = Rails.application.secrets.seat_geek_api_key || ENV['SEAT_GEEK_API_KEY']
        response = HTTParty.get("https://api.seatgeek.com/2/events?sort=score.desc&q=music+festival&per_page=52&client_id=#{@seatgeek}") 
        recent = HTTParty.get("https://api.seatgeek.com/2/events?sort=datetime_utc.asc&q=music+festival&per_page=52&client_id=#{@seatgeek}") 
        near = HTTParty.get("https://api.seatgeek.com/2/events?sort=datetime_utc.asc&q=music+festival&per_page=52&geoip=true&client_id=#{@seatgeek}")
        newly_announced = HTTParty.get("https://api.seatgeek.com/2/events?sort=announce_date.desc&q=music+festival&per_page=25&client_id=#{@seatgeek}")  
        @res = JSON.parse response.to_s, symbolize_names: true
        @recent = JSON.parse recent.to_s, symbolize_names: true
        @near = JSON.parse near.to_s, symbolize_names: true
        @newly = JSON.parse newly_announced.to_s, symbolize_names: true
    end

    def show
        params[:id]
        @seatgeek = Rails.application.secrets.seat_geek_api_key || ENV['SEAT_GEEK_API_KEY']
        @map = Rails.application.secrets.google_maps_api_key || ENV['GOOGLE_MAPS_API_KEY']
        response = HTTParty.get("https://api.seatgeek.com/2/events/#{params[:id]}?client_id=#{@seatgeek}") 
        @res = JSON.parse response.to_s, symbolize_names: true
        @performer_id = @res[:performers][0][:id]
        recommendation = HTTParty.get("https://api.seatgeek.com/2/recommendations/performers?performers.id=#{@performer_id}&client_id=#{@seatgeek}")
        @rec = JSON.parse recommendation.to_s, symbolize_names: true
    end

    def profile
        
    end


    def create 
        
    end

    def favorite
        if user_signed_in?
            @seatgeek = Rails.application.secrets.seat_geek_api_key || ENV['SEAT_GEEK_API_KEY']
            response = HTTParty.get("https://api.seatgeek.com/2/events/#{params[:id]}?client_id=#{@seatgeek}") 
            res = JSON.parse response.to_s, symbolize_names: true
            name = res[:title]
            venue = res[:venue][:name]
            location = res[:venue][:display_location]
            datetime = res[:datetime_local].to_date.strftime("%B %d, %Y")
            fest_id = params[:id]
            Favorite.create!(festival_id: fest_id, user_id: current_user.id, name: name, venue: venue, location: location, datetime: datetime)
        else
        end
    end

    def saved
        @faves = Favorite.where(user_id: current_user.id)
    end

    def deleted
        @faves_delete = Favorite.find(params[:id])
        @faves_delete.destroy
        redirect_to saved_path
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/festivals/index.html.erb
<!-- Simple header with scrollable tabs. -->
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
  <header class="mdl-layout__header">
    <div class="mdl-layout__header-row">
      <!-- Title -->
      <span class="mdl-layout-title"><%= link_to 'Stretto', root_path %> </span>
    </div>
    <!-- Tabs -->
    <div class="mdl-layout__tab-bar mdl-js-ripple-effect">
      <a href="#scroll-tab-1" class="mdl-layout__tab is-active">Popular</a>
      <a href="#scroll-tab-2" class="mdl-layout__tab">Coming Soon</a>
      <a href="#scroll-tab-3" class="mdl-layout__tab">Near Me</a>
      <a href="#scroll-tab-4" class="mdl-layout__tab">Just Announced</a>
    </div>
  </header>
  <div class="mdl-layout__drawer mdl-color--grey-900">
    <span class="mdl-layout-title mdl-color-text--accent">Stretto</span>
    <nav class="mdl-navigation">
      <a class="mdl-navigation__link mdl-color-text--primary" href=<%= festivals_path %>>Explore</a>
      <% if user_signed_in? %>
        <a class="mdl-navigation__link mdl-color-text--primary" href=<%= saved_path(current_user.id) %>>Favorites</a>
        <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "mdl-navigation__link mdl-color-text--primary") %>
      <% else %>
        <%= link_to('Login', new_user_session_path, class: "mdl-navigation__link mdl-color-text--primary") %>
      <% end %>
    </nav>
  </div>
  <main class="mdl-layout__content">
    <section class="mdl-layout__tab-panel is-active" id="scroll-tab-1">
      <div class="page-content">
        <h1>Most Popular</h1>
        <div class="festival-card">
          <% @res[:events].each do |e| %>
              <div class="festival-card-container mdl-shadow--4dp">
                <div class="festival-card-image-tile"
                  <% if e[:performers][0][:images][:huge] === nil %>
                      style='background-image: url("https://d49r1np2lhhxv.cloudfront.net/www/photos/EXITFestival2017_V1_1bxm6p2.jpg"); 
                      background-repeat: no-repeat; background-size: cover;' 
                  <% else %>
                      style='background-image: url(<%= e[:performers][0][:images][:huge] %>); 
                      background-repeat: no-repeat; background-size: cover;'
                  <% end %>
                  >
                  <div class="festival-title">
                    <h5><%= e[:title]%></h5>
                  </div>
                  <div class="overlay mdl-color--accent"></div>
                </div>
                <div class="festival-info">
                  <div><h5><%= e[:venue][:name]%></h5></div>
                  <div class="festival-location mdl-color-text--accent">
                    <%= e[:venue][:display_location]%>
                  </div>
                </div>

                <div class="festival-time mdl-color-text--accent"><%= e[:datetime_local].to_time.strftime("%a %b %d, %Y") %></div>
                <div class="festival-time mdl-color-text--accent"><%= e[:datetime_local].to_time.strftime("%-I:%M %p") %></div>
                <br>
                <div class="tickets-link">
                  <a href=<%=e[:url] %> target="_blank" class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">
                      BUY TICKETS
                  </a>
                  <% if e[:stats][:average_price] === nil %>
                        <span>Price: Not Available</span>
                    <% else %>
                        <span>starting at: $<%= e[:stats][:lowest_price].round%>.00</span>
                    <% end %>
                  
                  <div class="tickets-link" id="link-btn">
                    <a href=<%=festival_path(e[:id]) %> class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect mdl-color-text--white mdl-color--primary">
                        INFO
                    </a>
                  </div>
                </div>
              </div>
          <% end %>
        </div>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      </div>
    </section>
    <section class="mdl-layout__tab-panel" id="scroll-tab-2">
      <div class="page-content">
          <h1>Coming Soon</h1>
        <div class="festival-card">
          <% @recent[:events].each do |e| %>
              <div class="festival-card-container mdl-shadow--4dp">
                <div class="festival-card-image-tile"
                  <% if e[:performers][0][:images][:huge] === nil %>
                      style='background-image: url("https://d49r1np2lhhxv.cloudfront.net/www/photos/EXITFestival2017_V1_1bxm6p2.jpg"); 
                      background-repeat: no-repeat; background-size: cover;' 
                  <% else %>
                      style='background-image: url(<%= e[:performers][0][:images][:huge] %>); 
                      background-repeat: no-repeat; background-size: cover;'
                  <% end %>
                  >
                  <div class="festival-title">
                    <h5><%= e[:title]%></h5>
                  </div>
                  <div class="overlay mdl-color--accent"></div>
                </div>
                <div class="festival-info">
                  <div><h5><%= e[:venue][:name]%></h5></div>
                  <div class="festival-location mdl-color-text--accent">
                    <%= e[:venue][:display_location]%>
                  </div>
                </div>

                <div class="festival-time mdl-color-text--accent"><%= e[:datetime_local].to_time.strftime("%a %b %d, %Y") %></div>
                <div class="festival-time mdl-color-text--accent"><%= e[:datetime_local].to_time.strftime("%-I:%M %p") %></div>
                <br>
                <div class="tickets-link">
                  <a href=<%=e[:url] %> target="_blank" class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">
                      BUY TICKETS
                  </a>
                  <% if e[:stats][:average_price] === nil %>
                        <span>Price: Not Available</span>
                    <% else %>
                        <span>starting at: $<%= e[:stats][:lowest_price].round%>.00</span>
                    <% end %>
                  
                  <div class="tickets-link" id="link-btn">
                    <a href=<%=festival_path(e[:id]) %> class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect mdl-color-text--accent mdl-color--primary">
                        INFO
                    </a>
                  </div>
                </div>
              </div>
          <% end %>
        </div>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      </div>
    </section>
    <section class="mdl-layout__tab-panel" id="scroll-tab-3">
      <div class="page-content">
        <h1>Concerts Near Me</h1>
        <div class="festival-card">
          <% @near[:events].each do |e| %>
              <div class="festival-card-container mdl-shadow--4dp">
                <div class="festival-card-image-tile"
                  <% if e[:performers][0][:images][:huge] === nil %>
                      style='background-image: url("https://d49r1np2lhhxv.cloudfront.net/www/photos/EXITFestival2017_V1_1bxm6p2.jpg"); 
                      background-repeat: no-repeat; background-size: cover;' 
                  <% else %>
                      style='background-image: url(<%= e[:performers][0][:images][:huge] %>); 
                      background-repeat: no-repeat; background-size: cover;'
                  <% end %>
                  >
                  <div class="festival-title">
                    <h5><%= e[:title]%></h5>
                  </div>
                  <div class="overlay mdl-color--accent"></div>
                </div>
                <div class="festival-info">
                  <div><h5><%= e[:venue][:name]%></h5></div>
                  <div class="festival-location mdl-color-text--accent">
                    <%= e[:venue][:display_location]%>
                  </div>
                </div>

                <div class="festival-time mdl-color-text--accent"><%= e[:datetime_local].to_time.strftime("%a %b %d, %Y") %></div>
                <div class="festival-time mdl-color-text--accent"><%= e[:datetime_local].to_time.strftime("%-I:%M %p") %></div>
                <br>
                <div class="tickets-link">
                  <a href=<%=e[:url] %> target="_blank" class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">
                      BUY TICKETS
                  </a>
                  <% if e[:stats][:average_price] === nil %>
                        <span>Price: Not Available</span>
                    <% else %>
                        <span>starting at: $<%= e[:stats][:lowest_price].round%>.00</span>
                    <% end %>
                  
                  <div class="tickets-link" id="link-btn">
                    <a href=<%=festival_path(e[:id]) %> class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect mdl-color-text--accent mdl-color--primary">
                        INFO
                    </a>
                  </div>
                </div>
              </div>
          <% end %>
        </div>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
    </section>
    <section class="mdl-layout__tab-panel" id="scroll-tab-4">
      <div class="page-content">
        <h1>Recently Announced</h1>
        <div class="festival-card">
          <% @newly[:events].each do |e| %>
              <div class="festival-card-container mdl-shadow--4dp">
                <div class="festival-card-image-tile"
                  <% if e[:performers][0][:images][:huge] === nil %>
                      style='background-image: url("https://d49r1np2lhhxv.cloudfront.net/www/photos/EXITFestival2017_V1_1bxm6p2.jpg"); 
                      background-repeat: no-repeat; background-size: cover;' 
                  <% else %>
                      style='background-image: url(<%= e[:performers][0][:images][:huge] %>); 
                      background-repeat: no-repeat; background-size: cover;'
                  <% end %>
                  >
                  <div class="festival-title">
                    <h5><%= e[:title]%></h5>
                  </div>
                  <div class="overlay mdl-color--accent"></div>
                </div>
                <div class="festival-info">
                  <div><h5><%= e[:venue][:name]%></h5></div>
                  <div class="festival-location mdl-color-text--accent">
                    <%= e[:venue][:display_location]%>
                  </div>
                </div>

                <div class="festival-time mdl-color-text--accent"><%= e[:datetime_local].to_time.strftime("%a %b %d, %Y") %></div>
                <div class="festival-time mdl-color-text--accent"><%= e[:datetime_local].to_time.strftime("%-I:%M %p") %></div>
                <br>
                <div class="tickets-link">
                  <a href=<%=e[:url] %> target="_blank" class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">
                      BUY TICKETS
                  </a>
                  <% if e[:stats][:average_price] === nil %>
                        <span>Price: Not Available</span>
                    <% else %>
                        <span>starting at: $<%= e[:stats][:lowest_price].round%>.00</span>
                    <% end %>
                  
                  <div class="tickets-link" id="link-btn">
                    <a href=<%=festival_path(e[:id]) %> class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect mdl-color-text--accent mdl-color--primary">
                        INFO
                    </a>
                  </div>
                </div>
              </div>
          <% end %>
        </div>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
    </section>
  </main>
</div>

app/views/festivals/profile.html.erb
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
  <header class="mdl-layout__header">
    <div class="mdl-layout__header-row">
      <!-- Title -->
      <span class="mdl-layout-title"><%= link_to 'Stretto', root_path %> </span>
      <!-- Add spacer, to align navigation to the right -->
      <div class="mdl-layout-spacer"></div>
      <!-- Navigation. We hide it in small screens. -->
      <nav class="mdl-navigation mdl-layout--large-screen-only">
        <a class="mdl-navigation__link mdl-color-text--white" href=<%= festivals_path%>>Explore</a>
        <% if user_signed_in? %>
        <%= link_to('Profile', profile_path, class: "mdl-navigation__link mdl-color-text--white") %>
        <%= link_to('Favorites', saved_path, class: "mdl-navigation__link mdl-color-text--white") %>
        <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "mdl-navigation__link mdl-color-text--white") %>
        <% else %>
        <%= link_to('Login', new_user_session_path, class: "mdl-navigation__link mdl-color-text--white") %>
      <% end %>
      </nav>
    </div>
  </header>
  <div class="mdl-layout__drawer mdl-color--grey-900">
    <span class="mdl-layout-title mdl-color-text--accent">Stretto</span>
    <nav class="mdl-navigation">
      <a class="mdl-navigation__link mdl-color-text--primary" href=<%= festivals_path %>>Explore</a>
      <% if user_signed_in? %>
        <a class="mdl-navigation__link mdl-color-text--primary" href=<%= saved_path(current_user.id) %>>Favorites</a>
        <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "mdl-navigation__link mdl-color-text--primary") %>
      <% else %>
        <%= link_to('Login', new_user_session_path, class: "mdl-navigation__link mdl-color-text--primary") %>
      <% end %>
    </nav>
  </div>
<h2>This is the user profile page...</h2>

app/views/festivals/saved.html.erb
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
  <header class="mdl-layout__header">
    <div class="mdl-layout__header-row">
      <!-- Title -->
      <span class="mdl-layout-title"><%= link_to 'Stretto', root_path %> </span>
      <!-- Add spacer, to align navigation to the right -->
      <div class="mdl-layout-spacer"></div>
      <!-- Navigation. We hide it in small screens. -->
      <nav class="mdl-navigation mdl-layout--large-screen-only">
        <a class="mdl-navigation__link mdl-color-text--white" href=<%= festivals_path%>>Explore</a>
        <% if user_signed_in? %>
        <%= link_to('Favorites', saved_path, class: "mdl-navigation__link mdl-color-text--white") %>
        <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "mdl-navigation__link mdl-color-text--white") %>
        <% else %>
        <%= link_to('Login', new_user_session_path, class: "mdl-navigation__link mdl-color-text--white") %>
      <% end %>
      </nav>
    </div>
  </header>
  <div class="mdl-layout__drawer mdl-color--grey-900">
    <span class="mdl-layout-title mdl-color-text--accent">Stretto</span>
    <nav class="mdl-navigation">
      <a class="mdl-navigation__link mdl-color-text--primary" href=<%= festivals_path %>>Explore</a>
      <% if user_signed_in? %>
        <a class="mdl-navigation__link mdl-color-text--primary" href=<%= saved_path(current_user.id) %>>Favorites</a>
        <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "mdl-navigation__link mdl-color-text--primary") %>
      <% else %>
        <%= link_to('Login', new_user_session_path, class: "mdl-navigation__link mdl-color-text--primary") %>
      <% end %>
    </nav>
  </div>

<div class="fav-background">
    <table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp mdl-color--primary">
    <% @faves.each do |f| %>
        <thead>
            <tr>
                <th class="mdl-data-table__cell--non-numeric mdl-color-text--purple-50 table_data" style="font-size: 14pt; font-weight: 200;"><%= f[:name] %></th>
                <th class="mdl-color-text--purple-50" style="font-size: 14pt; font-weight: 200;"><%= f[:venue] %></th>
                <th class="mdl-color-text--purple-50" style="font-size: 14pt; font-weight: 200;"><%= f[:location] %></th>
                <th class="mdl-color-text--purple-50" style="font-size: 14pt; font-weight: 200;"><%= f[:datetime] %></th>
                <th class="mdl-color-text--purple-50" style="font-size: 14pt;"><i class="material-icons" style="font-weight: 800;"><%= link_to('clear', deleted_path(f[:id]), method: :delete)%></i></th>
            </tr>
        </thead>
    <% end %>
    </table>
</div>

app/views/festivals/show.html.erb
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
  <header class="mdl-layout__header">
    <div class="mdl-layout__header-row">
      <!-- Title -->
      <span class="mdl-layout-title"><%= link_to 'Stretto', root_path %> </span>
      <!-- Add spacer, to align navigation to the right -->
      <div class="mdl-layout-spacer"></div>
      <!-- Navigation. We hide it in small screens. -->
      <nav class="mdl-navigation mdl-layout--large-screen-only">
        <a class="mdl-navigation__link mdl-color-text--white" href=<%= festivals_path%>>Explore</a>
        <% if user_signed_in? %>
        <%= link_to('Profile', profile_path, class: "mdl-navigation__link mdl-color-text--white") %>
        <%= link_to('Favorites', saved_path, class: "mdl-navigation__link mdl-color-text--white") %>
        <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "mdl-navigation__link mdl-color-text--white") %>
        <% else %>
        <%= link_to('Login', new_user_session_path, class: "mdl-navigation__link mdl-color-text--white") %>
      <% end %>
      </nav>
    </div>
  </header>
  <div class="mdl-layout__drawer mdl-color--grey-900">
    <span class="mdl-layout-title mdl-color-text--accent">Stretto</span>
    <nav class="mdl-navigation">
      <a class="mdl-navigation__link mdl-color-text--primary" href=<%= festivals_path %>>Explore</a>
      <% if user_signed_in? %>
        <a class="mdl-navigation__link mdl-color-text--primary" href=<%= saved_path(current_user.id) %>>Favorites</a>
        <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "mdl-navigation__link mdl-color-text--primary") %>
      <% else %>
        <%= link_to('Login', new_user_session_path, class: "mdl-navigation__link mdl-color-text--primary") %>
      <% end %>
    </nav>
  </div>
  <div class="show-background">
    <main class="mdl-layout__content">
      <div class="page-content">
          <br>
          <div class"page-header">
          <div class="s-pg-grid-flex">
          <div class="s-pg-layout">
            <div class="header-container">
              <div class="header-info mdl-color--teal-400 mdl-shadow--8dp">
                <h3><%= @res[:title]%></h3>
                <br>
                <h5><%= @res[:venue][:name] %></h5>
                <h5><%= @res[:venue][:address] %></h5>
                <h5><%= @res[:venue][:display_location] %></h5>
                <h5><%= @res[:datetime_local].to_date.strftime("%B %d, %Y") %></h5>
                <br>
                <%= button_to "Add to Favorites", favorite_path(@res[:id]), method: :post, id: "faves", class: "mdl-button mdl-js-button mdl-button--raised mdl-color--primary mdl-color-text--teal-50"%>
                <div id="fave-pop" class="mdl-js-snackbar mdl-snackbar">
                  <div class="mdl-snackbar__text"></div>
                  <button class="mdl-snackbar__action" type="button"></button>
                </div>
                <% if user_signed_in? %>
                  <script>
                    (function() {
                      'use strict';
                      var snackbarContainer = document.querySelector('#fave-pop');
                      var showFaveButton = document.querySelector('#faves');
                      showFaveButton.addEventListener('click', function() {
                        'use strict';
                        var data = {message: 'Added to Favorites!'};
                        snackbarContainer.MaterialSnackbar.showSnackbar(data);
                      });
                    }());
                  </script>
                
                <% else %>

                  <script>
                    (function() {
                      'use strict';
                      var snackbarContainer = document.querySelector('#fave-pop');
                      var showFaveButton = document.querySelector('#faves');
                      showFaveButton.addEventListener('click', function() {
                        'use strict';
                        var data = {message: 'Sign in to add favorites'};
                        snackbarContainer.MaterialSnackbar.showSnackbar(data);
                      });
                    }());
                  </script>

                <% end %>
                <br>
                <div class="buy-now-btn">
                  <button class="mdl-button mdl-js-button"><a class="mdl-color-text--teal-50" href=<%= @res[:url]%> target="_blank">BUY TICKETS</a>
                  </button>
                </div>
              </div>
              <div class="performer-info mdl-color-text--accent">
                <div class="mdl-color-text--teal-50">Starring:</div>
                <br>
                <% @res[:performers].each do |p|%>
                    <% if @res[:short_title].split(" ")[0].downcase != p[:short_name].split(" ")[0].downcase %>
                        <div><%= p[:short_name]%></div>
                    <% else %>
                      <h3>TBD</h3>
                    <% end %>
                <% end %>
              </div>
            </div>
          </div>
      </div>
          <div class="recommendations">
            <h1 class="mdl-color-text--accent">You may also be interested in...</h1>
            <div class="s-artist-rec">
              <% @rec[:recommendations].each do |r| %>
                    <div class="rec-artist-card">
                      <div class="rec-info">
                        <div class="rec-name ">
                          <h6><%= r[:performer][:short_name] %></h6>
                        </div>
                      </div>
                    </div>
              <% end %>
            </div>
          </div>
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
    </main>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StrettoApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.red-teal.min.css">
    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
  </head>

  <body>
    <%= yield %>

    <script type="text/javascript">
      document.addEventListener('turbolinks:load', function() {
          componentHandler.upgradeDom();
      });
    </script>

  </body>
</html>